# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1e\n\x0eRequestMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x0fResponseMessage\x12\x10\n\x08greeting\x18\x01 \x01(\t2L\n\tMyService\x12?\n\x08MyMethod\x12\x17.example.RequestMessage\x1a\x18.example.ResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUESTMESSAGE']._serialized_start=26
  _globals['_REQUESTMESSAGE']._serialized_end=56
  _globals['_RESPONSEMESSAGE']._serialized_start=58
  _globals['_RESPONSEMESSAGE']._serialized_end=93
  _globals['_MYSERVICE']._serialized_start=95
  _globals['_MYSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
